# A sample Gemfile
source "https://rubygems.org"

gem "sinatra"
gem "mysql2-cs-bind"
gem "rack-flash3"
gem "unicorn"
gem "foreman"
gem "rack-lineprof", github: "kainosnoema/rack-lineprof"
gem "redis"
gem "rack-session-redis"
